import = ["~/.config/alacritty/theme.toml"]
live_config_reload = true
shell = { program = "tmux", args = ["new-session", "-A", "-s", "general"] }

[bell]
duration = 600
color = "#292929"
animation = "Ease"
command = { program = "pw-cat", args = [
    "-p", "/home/fuad/.config/sounds/bell.ogg",
] }

[cursor]
thickness = 0.1
unfocused_hollow = true
style = { blinking = "Off", shape = "Beam" }

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 16
builtin_box_drawing = true
normal = { family = "Fira Code" }

[mouse]
hide_when_typing = true

[window]
dimensions = { columns = 140, lines = 36 }
opacity = 1
blur = false
dynamic_title = true
padding = { x = 10, y = 10 }
decorations = "None"
